#!/bin/python3
# Copyright 2019 Red Hat
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

"""A script to setup kube config from pod
"""

from base64 import b64encode
from pathlib import Path

kube_config = Path("~/.kube/config").expanduser()
kube_config.parent.mkdir(exist_ok=True, parents=True)
kube_config.write_text("""
apiVersion: v1
kind: Config
preferences: {}
clusters:
- cluster:
    server: https://10.43.0.1:8043
    insecure-skip-tls-verify: true
  name: local
users:
- name: default
  user:
    token: %s
contexts:
- context:
    cluster: local
    user: default
    namespace: silverkube
  name: local
current-context: local
""" % (Path("/run/secrets/kubernetes.io/serviceaccount/token").read_text()))
